#!/bin/sh

set -e

if [ -z $BASIC_AUTH_USERNAME ]; then
  echo >&2 "BASIC_AUTH_USERNAME must be set"
  exit 1
fi

if [ -z $BASIC_AUTH_PASSWORD ]; then
  echo >&2 "BASIC_AUTH_PASSWORD must be set"
  exit 1
fi

if [ -z $PROXY_PASS ]; then
  echo >&2 "PROXY_PASS must be set"
  exit 1
fi

htpasswd -bBc /etc/nginx/.htpasswd $BASIC_AUTH_USERNAME $BASIC_AUTH_PASSWORD
htpasswd -bB /etc/nginx/.htpasswd	TSN1 welcome2020@WM20
htpasswd -bB /etc/nginx/.htpasswd	TSN2 welcome2020@WM20
htpasswd -bB /etc/nginx/.htpasswd	TSN3 welcome2020@WM20
htpasswd -bB /etc/nginx/.htpasswd	TSN4 welcome2020@WM20
htpasswd -bB /etc/nginx/.htpasswd	TSN5 welcome2020@WM20
htpasswd -bB /etc/nginx/.htpasswd	pasuth@gmail.com OgyE6068+
htpasswd -bB /etc/nginx/.htpasswd	akalnina19@gmail.com XoyZ3757*
htpasswd -bB /etc/nginx/.htpasswd	cpronman@theathletic.com FbkA2430+
htpasswd -bB /etc/nginx/.htpasswd	martin.leclerc@radio-canada.ca AeeY7159+
htpasswd -bB /etc/nginx/.htpasswd	dtuboltseva1995@gmail.com UheK5285*
htpasswd -bB /etc/nginx/.htpasswd	samartsevmax@mail.ru EsfJ8034+
htpasswd -bB /etc/nginx/.htpasswd	S.GALKEVICH@RIAN.RU KftK6437+
htpasswd -bB /etc/nginx/.htpasswd	malin.fransson@dn.se MtiX9693*
htpasswd -bB /etc/nginx/.htpasswd	michal.cerveny@dennikn.sk VysN3837*
htpasswd -bB /etc/nginx/.htpasswd	peter.kovac@projektn.sk HkdA6083+
htpasswd -bB /etc/nginx/.htpasswd	matej.ondrisek@gmail.com TueC4182*
htpasswd -bB /etc/nginx/.htpasswd	stefan.bugan@projektn.sk FdsU6376*
htpasswd -bB /etc/nginx/.htpasswd	cmpeters10@gmail.com CckP6459+
htpasswd -bB /etc/nginx/.htpasswd	day.shevchenko@gmail.com GneN3098+
htpasswd -bB /etc/nginx/.htpasswd	karl.huber@orf.at OpvO1024+
htpasswd -bB /etc/nginx/.htpasswd	martin.quendler@kleinezeitung.at SfrS7243*
htpasswd -bB /etc/nginx/.htpasswd	anders@sportnyhet.com SwpR6906+
htpasswd -bB /etc/nginx/.htpasswd	Steven.ellis@thehockeynews.com NbbL5276+
htpasswd -bB /etc/nginx/.htpasswd	andrew@onefm.ca NjgN7074+
htpasswd -bB /etc/nginx/.htpasswd	kevin.dube@quebecormedia.com MknO6860+
htpasswd -bB /etc/nginx/.htpasswd	rkennedy@thehockeynews.com KhfY2448*
htpasswd -bB /etc/nginx/.htpasswd	Marc-Eric.Bouchard@radio-canada.ca UfoK6509+
htpasswd -bB /etc/nginx/.htpasswd	martin.vano@ringieraxelspringer.sk DieS3407+
htpasswd -bB /etc/nginx/.htpasswd	amy@allhabs.net XhcF9244*
htpasswd -bB /etc/nginx/.htpasswd	jurewicz.chris@gmail.com UauS7554+
htpasswd -bB /etc/nginx/.htpasswd	tommi.willberg@hbl.fi XcqM9633*
htpasswd -bB /etc/nginx/.htpasswd	glepage@nhl.com MepK1378+
htpasswd -bB /etc/nginx/.htpasswd	Patrick.henri@radio-canada.ca YxsH9423+
htpasswd -bB /etc/nginx/.htpasswd	tbaines@postmedia.com OipD5416+
htpasswd -bB /etc/nginx/.htpasswd	dvandiest@postmedia.com ReoV1189+
htpasswd -bB /etc/nginx/.htpasswd	Adam.cook@bellmedia.ca JjdU4334+
htpasswd -bB /etc/nginx/.htpasswd	al@onefm.ca XuuF9205+
htpasswd -bB /etc/nginx/.htpasswd	jcuthbert@verizonmedia.com DrgO3228+
htpasswd -bB /etc/nginx/.htpasswd	rob@dailyhive.com OxbI7905*
htpasswd -bB /etc/nginx/.htpasswd	alexandre.gascon@radio-canada.ca JchF7236*
htpasswd -bB /etc/nginx/.htpasswd	nhlbymatty@shaw.ca LfpB2993+
htpasswd -bB /etc/nginx/.htpasswd	u20@hockeyfans.ch NspM8342+
htpasswd -bB /etc/nginx/.htpasswd	gsoutham@postmedia.com RykJ5380*
htpasswd -bB /etc/nginx/.htpasswd	jean-francois.vachon@radio-canada.ca AhmP9972+
htpasswd -bB /etc/nginx/.htpasswd	robert.tychkowski@sunmedia.ca JeoQ6759*
htpasswd -bB /etc/nginx/.htpasswd	Jackie.Spiegel@dazn.com VokO5748+
htpasswd -bB /etc/nginx/.htpasswd	rpyette@postmedia.com WneC9670*
htpasswd -bB /etc/nginx/.htpasswd	kbalzer@princegeorgematters.com ZtsT4392*
htpasswd -bB /etc/nginx/.htpasswd	b.pfeifer@oe24.at VinA7488+
htpasswd -bB /etc/nginx/.htpasswd	jfransonphoto@gmail.com KaiA1482+
htpasswd -bB /etc/nginx/.htpasswd	Jouninposti@shaw.ca MmyU9746*
htpasswd -bB /etc/nginx/.htpasswd	tuomas@gronman.fi HtzR5333+
htpasswd -bB /etc/nginx/.htpasswd	yurinov@yandex.ru AjaL9705*
htpasswd -bB /etc/nginx/.htpasswd	rcohen@sportsology.net VijE9905+
htpasswd -bB /etc/nginx/.htpasswd	squire.barnes@globalnews.ca GtzS4042*
htpasswd -bB /etc/nginx/.htpasswd	barry.deley@globalnews.ca AliR9179+
htpasswd -bB /etc/nginx/.htpasswd	pekka_kaidesoja@discovery.com SbuN6909+
htpasswd -bB /etc/nginx/.htpasswd	petri.heikkinen@i-mediat.fi UafQ8979*
htpasswd -bB /etc/nginx/.htpasswd	crotter@mamo.de GisP1555*
htpasswd -bB /etc/nginx/.htpasswd	redaktion@eishockey-online.com PkwY8710+
htpasswd -bB /etc/nginx/.htpasswd	r.solovyov@khl.ru UdsX5013+
htpasswd -bB /etc/nginx/.htpasswd	jaschick@t-online.de KjxJ6954*
htpasswd -bB /etc/nginx/.htpasswd	matej.deraj@gmail.com EsbV3209+
htpasswd -bB /etc/nginx/.htpasswd	tomas.prokop@gmail.com PryD6289+
htpasswd -bB /etc/nginx/.htpasswd	sascha.fey@keystone-sda.ch BxaX2129+
htpasswd -bB /etc/nginx/.htpasswd	puck.kristina@dpa.com CxkU6118*
htpasswd -bB /etc/nginx/.htpasswd	jan.skvor@sport.cz ZzuZ8452*
htpasswd -bB /etc/nginx/.htpasswd	daniel.goldstein19@gmail.com TovW5646+
htpasswd -bB /etc/nginx/.htpasswd	dimas070712@gmail.com SxhR2280+
htpasswd -bB /etc/nginx/.htpasswd	marek.burkert@pravo.cz QapL2504+
htpasswd -bB /etc/nginx/.htpasswd	lappe.carsten@dpa.com VnzP4303+
htpasswd -bB /etc/nginx/.htpasswd	robert.rampa@idnes.cz VteI9804*
htpasswd -bB /etc/nginx/.htpasswd	lucie.cermanova@iprima.cz IvdF7895+
htpasswd -bB /etc/nginx/.htpasswd	jaroslav.tomas@idnes.cz IhqD9720*
htpasswd -bB /etc/nginx/.htpasswd	pavellysenkov76@mail.ru AdgN4303+
htpasswd -bB /etc/nginx/.htpasswd	mmorreale@nhl.com TsaK9907*
htpasswd -bB /etc/nginx/.htpasswd	artemvsoloviev@gmail.com DwaD1151*
htpasswd -bB /etc/nginx/.htpasswd	bohuslav.stehno@idnes.cz QzxK7294+
htpasswd -bB /etc/nginx/.htpasswd	samcoz@rogers.com JfsP9102+
htpasswd -bB /etc/nginx/.htpasswd	RETO.MUELLER@MYSPORTS.CH PkqV5995*
htpasswd -bB /etc/nginx/.htpasswd	lamedia@telus.net JmkR7536*
htpasswd -bB /etc/nginx/.htpasswd	demidovsm@gmail.com GxkU4187+
htpasswd -bB /etc/nginx/.htpasswd	langrmichael@gmail.com NzwS5629+
htpasswd -bB /etc/nginx/.htpasswd	JDBurke@EliteProspects.com PhcL3985*
htpasswd -bB /etc/nginx/.htpasswd	magnity@mail.ru JpiS4189*
htpasswd -bB /etc/nginx/.htpasswd	Jon.Abbott@bellmedia.ca QemZ5379+
htpasswd -bB /etc/nginx/.htpasswd	emil.forsberg@tt.se HddF7069*
htpasswd -bB /etc/nginx/.htpasswd	julie@eliteprospects.com TbgT7401*
htpasswd -bB /etc/nginx/.htpasswd	kevin.karius@globalnews.ca ZdwZ4878*
htpasswd -bB /etc/nginx/.htpasswd	sth@eishockey.com VukM4685*
htpasswd -bB /etc/nginx/.htpasswd	Christian.Goebel@eishockey.com DmvC3117+
htpasswd -bB /etc/nginx/.htpasswd	jan.denemark@cncenter.cz JatX6618+
htpasswd -bB /etc/nginx/.htpasswd	mpa2nd@hotmail.com SxiJ7705+
htpasswd -bB /etc/nginx/.htpasswd	petteri.ikonen@stt-lehtikuva.fi DtiV3193+
htpasswd -bB /etc/nginx/.htpasswd	lukyno.80@seznam.cz NgcX7210*
htpasswd -bB /etc/nginx/.htpasswd	adam.johansson@expressen.se JvgA6664+
htpasswd -bB /etc/nginx/.htpasswd	sihvonen@aol.com DggR6863*
htpasswd -bB /etc/nginx/.htpasswd	carolrunner@gmail.com IubJ9979+
htpasswd -bB /etc/nginx/.htpasswd	Daniel.teissl@orf.at LyuA2717*
htpasswd -bB /etc/nginx/.htpasswd	bernd.schwickerath@yahoo.de ZocP1830+
htpasswd -bB /etc/nginx/.htpasswd	stefan.grueneis@apa.at AepB2050*
htpasswd -bB /etc/nginx/.htpasswd	lassi.kuisma@iltalehti.fi PxgR2017+
htpasswd -bB /etc/nginx/.htpasswd	c.mueller@positivelines.com DihI6283*
htpasswd -bB /etc/nginx/.htpasswd	mzislis@mail.ru HblK5646+
htpasswd -bB /etc/nginx/.htpasswd	jachim@hokej.cz VuiV4379+
htpasswd -bB /etc/nginx/.htpasswd	cf@cfetzer.com ZfvT2406+
htpasswd -bB /etc/nginx/.htpasswd	voltr@hokej.cz XbgM9819*
htpasswd -bB /etc/nginx/.htpasswd	maximilian.waitl@thinxpool.de BzmT3983+
htpasswd -bB /etc/nginx/.htpasswd	niclas.viberg@svenskafans.com QgcN3856*
htpasswd -bB /etc/nginx/.htpasswd	egorf@yandex.ru FgcR6344*
htpasswd -bB /etc/nginx/.htpasswd	mckristy@umich.edu CmdG5820*
htpasswd -bB /etc/nginx/.htpasswd	stephane.leroux@bellmedia.ca AxwL7306*
htpasswd -bB /etc/nginx/.htpasswd	meske@ushl.com TyiF9796*
htpasswd -bB /etc/nginx/.htpasswd	bstauffer@edmontonoilers.com PohI8493+
htpasswd -bB /etc/nginx/.htpasswd	roman.michel@somedia.ch JpdB6010+
htpasswd -bB /etc/nginx/.htpasswd	scarchidi@inquirer.com WahW2366+
htpasswd -bB /etc/nginx/.htpasswd	Jay.janower@globalnews.ca PkyQ7737*
htpasswd -bB /etc/nginx/.htpasswd	ekhopeter@gmail.com QjeJ9627+
htpasswd -bB /etc/nginx/.htpasswd	christian@cjob.com NzmA1496*
htpasswd -bB /etc/nginx/.htpasswd	gmoddejonge@postmedia.com SgbJ1853*
htpasswd -bB /etc/nginx/.htpasswd	joel.marklund@bildbyran.se JtbS2711*
htpasswd -bB /etc/nginx/.htpasswd	otto.palojarvi@sportcontent.fi AyyP8729*
htpasswd -bB /etc/nginx/.htpasswd	anssi.karjalainen@iltalehti.fi WpkF3920*
htpasswd -bB /etc/nginx/.htpasswd	sasha.huttunen@iltalehti.fi ArcR5783+
htpasswd -bB /etc/nginx/.htpasswd	matti.nyrhinen@mtv.fi QxsO5951+
htpasswd -bB /etc/nginx/.htpasswd	ilari.savonen@mtv.fi EwvI6934*
htpasswd -bB /etc/nginx/.htpasswd	kirsi.teiskonlahti@yle.fi EprD3318+
htpasswd -bB /etc/nginx/.htpasswd	harri.hepojarvi@iltalehti.fi InrQ5661+
htpasswd -bB /etc/nginx/.htpasswd	uffe.bodin@hockeysverige.se DhaA4390*
htpasswd -bB /etc/nginx/.htpasswd	axel.jeroma@eishockey.com HmzP6966+
htpasswd -bB /etc/nginx/.htpasswd	viktor.alner@svenskafans.com QyhT4640+
htpasswd -bB /etc/nginx/.htpasswd	roby.st-gelais@quebecormedia.com MiuI2675+
htpasswd -bB /etc/nginx/.htpasswd	linus.sunnervik@svenskafans.com GxoH8513+
htpasswd -bB /etc/nginx/.htpasswd	holmstalhand@gmail.com JptY2986*
htpasswd -bB /etc/nginx/.htpasswd	miikkalahtinen@hotmail.com JneQ1159+
htpasswd -bB /etc/nginx/.htpasswd	mans.karlsson@hockeysverige.se JfgU4467*
htpasswd -bB /etc/nginx/.htpasswd	matthew.black@bellmedia.ca UhiU6435*
htpasswd -bB /etc/nginx/.htpasswd	sami.hoffren@iltasanomat.fi JorS2977*
htpasswd -bB /etc/nginx/.htpasswd	swheeler@theathletic.com TskK6230+
htpasswd -bB /etc/nginx/.htpasswd	christianlarnold92@gmail.com HgdO3254*
htpasswd -bB /etc/nginx/.htpasswd	akimelman@nhl.com HxkX5268*
htpasswd -bB /etc/nginx/.htpasswd	mbakaj@perex.sk ZovF2102+
htpasswd -bB /etc/nginx/.htpasswd	sportsnethub@rci.rogers.com WonT6110+
htpasswd -bB /etc/nginx/.htpasswd	ville.touru@is.fi MeaW3321*
htpasswd -bB /etc/nginx/.htpasswd	abc@cp.org VvoY1138+
htpasswd -bB /etc/nginx/.htpasswd	johnwawrow59@outlook.com FiuD7654*
htpasswd -bB /etc/nginx/.htpasswd	Mark.Spector@rci.rogers.com GqhT4807*
htpasswd -bB /etc/nginx/.htpasswd	Rory.Boylen@sportsnet.ca JqdH6164+
htpasswd -bB /etc/nginx/.htpasswd	sonny.sachdeva@sportsnet.ca CenE9422*
htpasswd -bB /etc/nginx/.htpasswd	Ryan.Dixon@sportsnet.ca DjlN2528*
htpasswd -bB /etc/nginx/.htpasswd	Lauren.Li@rci.rogers.com IndZ1175*
htpasswd -bB /etc/nginx/.htpasswd	Gene.Principe@rci.rogers.com MklX7820*
htpasswd -bB /etc/nginx/.htpasswd	mitchbrown31@gmail.com JfkR1060*
htpasswd -bB /etc/nginx/.htpasswd	marc.delbes@lapressecanadienne.com ZnjE6349+
htpasswd -bB /etc/nginx/.htpasswd	oliverjensen@gmx.de AteF1712+
htpasswd -bB /etc/nginx/.htpasswd	jari.perkio@pp.inet.fi IybW2150*
htpasswd -bB /etc/nginx/.htpasswd	timop.uusitalo@yle.fi AezE7028*
htpasswd -bB /etc/nginx/.htpasswd	goran.sundberg@tt.se DdkN8665*
htpasswd -bB /etc/nginx/.htpasswd	tapani.salo@sanoma.com DwzW3791*
htpasswd -bB /etc/nginx/.htpasswd	saradeth@eishockeynews.de PrrC4105*
htpasswd -bB /etc/nginx/.htpasswd	johannadahleen@hotmail.com VueA7303+
htpasswd -bB /etc/nginx/.htpasswd	miska.miettinen92@gmail.com FtcE9862+
htpasswd -bB /etc/nginx/.htpasswd	bayer@eishockeynews.de VqzL3266*
htpasswd -bB /etc/nginx/.htpasswd	lars.weiske@sid.de HzfC1258*
htpasswd -bB /etc/nginx/.htpasswd	kagstrom65@hotmail.com FuhW5929+
htpasswd -bB /etc/nginx/.htpasswd	bagar@hokej.cz JqpY2692*
htpasswd -bB /etc/nginx/.htpasswd	joonas.jussila@ts.fi HskV1689*
htpasswd -bB /etc/nginx/.htpasswd	m.safin@fhr.ru XxfD5126+
htpasswd -bB /etc/nginx/.htpasswd	urs.berger@puckfans.at GjbZ2998*
htpasswd -bB /etc/nginx/.htpasswd	mikalaakso67@gmail.com KmlL8576+
htpasswd -bB /etc/nginx/.htpasswd	leo.runsas@jatkoaika.com KfkQ8596*
htpasswd -bB /etc/nginx/.htpasswd	Joshua.Beneteau@Sportsnet.ca PcaW7050*
htpasswd -bB /etc/nginx/.htpasswd	tuuli.maatta@jatkoaika.com ZleZ8661+
htpasswd -bB /etc/nginx/.htpasswd	eero.hurmerinta@jatkoaika.com UonK6081+
htpasswd -bB /etc/nginx/.htpasswd	codie.mclachlan@gmail.com PbcX9571+
htpasswd -bB /etc/nginx/.htpasswd	heikki.miettinen@hs.fi CgcI5683+
htpasswd -bB /etc/nginx/.htpasswd	artur89-ks@yandex.ru GgsP3494+
htpasswd -bB /etc/nginx/.htpasswd	skryl_a@inbox.ru HvpQ5226*
htpasswd -bB /etc/nginx/.htpasswd	rp@eishockey.com SblL8058*
htpasswd -bB /etc/nginx/.htpasswd	mattias.simonsen@yle.fi RfmG5335*
htpasswd -bB /etc/nginx/.htpasswd	robin.olausson@hotmail.com RdkW3810*
htpasswd -bB /etc/nginx/.htpasswd	donna.spencer@thecanadianpress.com NqnM1510*
htpasswd -bB /etc/nginx/.htpasswd	mike.koreen@thecanadianpress.com OfoN8139+
htpasswd -bB /etc/nginx/.htpasswd	michal.tegza@tasr.sk KriN3729*
htpasswd -bB /etc/nginx/.htpasswd	michal.juraska@tasr.sk OuzL5761*
htpasswd -bB /etc/nginx/.htpasswd	carl-magnus.langkvist@yle.fi NjiI4828+
htpasswd -bB /etc/nginx/.htpasswd	katarina.vilcek@gmail.com XegP5731*
htpasswd -bB /etc/nginx/.htpasswd	luke@ckrw.com RwnO7926+
htpasswd -bB /etc/nginx/.htpasswd	dean.bennett@thecanadianpress.com PixG7323+
htpasswd -bB /etc/nginx/.htpasswd	tim.cook@thecanadianpress.com ElgJ7667+
htpasswd -bB /etc/nginx/.htpasswd	jvsalminen@gmail.com YpyD3939*
htpasswd -bB /etc/nginx/.htpasswd	betka.takacsova22@gmail.com SpdA2451*
htpasswd -bB /etc/nginx/.htpasswd	mr.daff@mail.ru QveV3492*
htpasswd -bB /etc/nginx/.htpasswd	markdivver@gmail.com PfoV2239+
htpasswd -bB /etc/nginx/.htpasswd	petr.kaderabek@rozhlas.cz UjsG7496+
htpasswd -bB /etc/nginx/.htpasswd	frantisek.kuna@rozhlas.cz HcpS2911*
htpasswd -bB /etc/nginx/.htpasswd	alexander.gammel@eishockey.com AwsM5289*
htpasswd -bB /etc/nginx/.htpasswd	alessandro.serenrosso@gmail.com BcyZ5452*
htpasswd -bB /etc/nginx/.htpasswd	mats.ahlnas@yle.fi HvyY7548+
htpasswd -bB /etc/nginx/.htpasswd	alexander@hockeynews.se AwbJ6608+
htpasswd -bB /etc/nginx/.htpasswd	henrik.sjoberg@hockeynews.se KmsS9418+
htpasswd -bB /etc/nginx/.htpasswd	sebastian.von.eichwald@hockeynews.se JztH7870+
htpasswd -bB /etc/nginx/.htpasswd	peter.karlik@kurier.at WzzC6200*
htpasswd -bB /etc/nginx/.htpasswd	polak@ctk.cz JrrO4948+
htpasswd -bB /etc/nginx/.htpasswd	voves@mail.ctk.cz UrgM9657+
htpasswd -bB /etc/nginx/.htpasswd	john@hockeynews.se GacW8070*
htpasswd -bB /etc/nginx/.htpasswd	Hoven@MayorsManor.com DwiJ6587+
htpasswd -bB /etc/nginx/.htpasswd	daniel.polacek@aktualne.cz GucA8654+
htpasswd -bB /etc/nginx/.htpasswd	Guenter.Klein@merkur.de CcaN8328+
htpasswd -bB /etc/nginx/.htpasswd	harryt@usahockey.org FczH8038+
htpasswd -bB /etc/nginx/.htpasswd	jessrubenstein@comcast.net ZooA4396*
htpasswd -bB /etc/nginx/.htpasswd	michael.berger@orf.at VpaO3077+
htpasswd -bB /etc/nginx/.htpasswd	dieter.helbig@orf.at BhpX6432+
htpasswd -bB /etc/nginx/.htpasswd	elred.faisst@vsport.at PwsB9519+
htpasswd -bB /etc/nginx/.htpasswd	Bruno.montpetit@bellmedia.ca ZvtU1072+
htpasswd -bB /etc/nginx/.htpasswd	Bertrand.houle@bellmedia.ca UmsC5118*
htpasswd -bB /etc/nginx/.htpasswd	convocations@rds.ca OzwX7295+
htpasswd -bB /etc/nginx/.htpasswd	kmcgran@thestar.ca AwdD8465+
htpasswd -bB /etc/nginx/.htpasswd	glefrancois@lapresse.ca KigT7173*
htpasswd -bB /etc/nginx/.htpasswd	slorange@lapresse.ca FjoI8550*
htpasswd -bB /etc/nginx/.htpasswd	martin.dion@tva.ca ClbN7809+
htpasswd -bB /etc/nginx/.htpasswd	dana.mckiel@gmail.com MfdE4980+
htpasswd -bB /etc/nginx/.htpasswd	robin.short@thetelegram.com KokU6585*
htpasswd -bB /etc/nginx/.htpasswd	laykroyd@hotmail.com CmtL2760+
htpasswd -bB /etc/nginx/.htpasswd	moydartpress@sympatico.ca GucB7610+
htpasswd -bB /etc/nginx/.htpasswd	kruk@tass.ru MvmE3426*
htpasswd -bB /etc/nginx/.htpasswd	kartashov_a@tass.ru MbuV7560*
htpasswd -bB /etc/nginx/.htpasswd	dfhdfheirf@gmail.com KmcT9187*
htpasswd -bB /etc/nginx/.htpasswd	equador@list.ru PkoL5782+
htpasswd -bB /etc/nginx/.htpasswd	zamax80@bk.ru MimL6586+
htpasswd -bB /etc/nginx/.htpasswd	patrik.mitas@rtvs.sk IysZ2795*
htpasswd -bB /etc/nginx/.htpasswd	martin.balazik@rtvs.sk OilN9994*
htpasswd -bB /etc/nginx/.htpasswd	zlatica.mokra@rtvs.sk BtnE1927+
htpasswd -bB /etc/nginx/.htpasswd	tomas.zagiba@rtvs.sk EfkQ1030*
htpasswd -bB /etc/nginx/.htpasswd	tobias.jedeskog@tv4.se BnbR5018+
htpasswd -bB /etc/nginx/.htpasswd	hans.abrahamsson@aftonbladet.se IivQ5741*
htpasswd -bB /etc/nginx/.htpasswd	mattias.karlsson@aftonbladet.se LjlN2693+
htpasswd -bB /etc/nginx/.htpasswd	filip.lindfors@aftonbladet.se AcoO5102+
htpasswd -bB /etc/nginx/.htpasswd	anton.johansson@aftonbladet.se WddA2794*
htpasswd -bB /etc/nginx/.htpasswd	emelie.fredriksson@aftonbladet.se QpxE9084*
htpasswd -bB /etc/nginx/.htpasswd	andreas.kack@aftonbladet.se QynO1102*
htpasswd -bB /etc/nginx/.htpasswd	TJones@postmedia.com EjqL1160+
htpasswd -bB /etc/nginx/.htpasswd	quinn.phillips@globalnews.ca XjnZ7511+
htpasswd -bB /etc/nginx/.htpasswd	Jesse.Thomas@globalnews.ca OaeG8793+
htpasswd -bB /etc/nginx/.htpasswd	ethan.ready@jpbg.ca VncZ6253*
htpasswd -bB /etc/nginx/.htpasswd	emadziya@hockeycanada.ca QsdX7991+
htpasswd -bB /etc/nginx/.htpasswd	ssharkey@hockeycanada.ca HknI4776*
htpasswd -bB /etc/nginx/.htpasswd	dsaillant@hockeycanada.ca GagE3601*
htpasswd -bB /etc/nginx/.htpasswd	abrin@shaw.ca KesO5260+
htpasswd -bB /etc/nginx/.htpasswd	pablo.jarvinen@gmail.com MhsR2543*
htpasswd -bB /etc/nginx/.htpasswd	kimmo.oikarinen@finhockey.fi QusH3660*
htpasswd -bB /etc/nginx/.htpasswd	henna.malmberg@finhockey.fi DxmG9663+
htpasswd -bB /etc/nginx/.htpasswd	pasi.mennander@finhockey.fi VgbY2507*
htpasswd -bB /etc/nginx/.htpasswd	psenka@szlh.sk FhkO5373+
htpasswd -bB /etc/nginx/.htpasswd	kyselica@szlh.sk FteH1542+
htpasswd -bB /etc/nginx/.htpasswd	janosik@szlh.sk DwyZ1662+
htpasswd -bB /etc/nginx/.htpasswd	manuela.hess@sihf.ch KjaL4548*
htpasswd -bB /etc/nginx/.htpasswd	hans.boss@sihf.ch QirT7476+
htpasswd -bB /etc/nginx/.htpasswd	ruben.stark@deb-online.de WhbR8478+
htpasswd -bB /etc/nginx/.htpasswd	andrea.baader@deb-online.de AigK1833+
htpasswd -bB /etc/nginx/.htpasswd	M.Safin@fhr.ru OasB1266*
htpasswd -bB /etc/nginx/.htpasswd	a.kovtunenko@fhr.ru IdzG3384*
htpasswd -bB /etc/nginx/.htpasswd	a.ryzhikov@fhr.ru KmeO7343+
htpasswd -bB /etc/nginx/.htpasswd	Linus.Hugosson@swehockey.se DnnY2428*
htpasswd -bB /etc/nginx/.htpasswd	davef@usahockey.org OrkB5107*
htpasswd -bB /etc/nginx/.htpasswd	aaron.westendorf@usahockey.org NyaP1693+
htpasswd -bB /etc/nginx/.htpasswd	kyle.huson@usahockey.org KjbT7189+
htpasswd -bB /etc/nginx/.htpasswd	zikmund@czehockey.cz VdeY3406*
htpasswd -bB /etc/nginx/.htpasswd	kalat@czehockey.cz JjtF5493+
htpasswd -bB /etc/nginx/.htpasswd	russmann@eishockey.at ZaqS3426*
htpasswd -bB /etc/nginx/.htpasswd	weihs@eishockey.at NgcI7546+
htpasswd -bB /etc/nginx/.htpasswd	steiss@iihf.com RcxW8376+
htpasswd -bB /etc/nginx/.htpasswd	merk@iihf.com AhkE3750+
htpasswd -bB /etc/nginx/.htpasswd	storie.serres@gmail.com EgeH3872*
htpasswd -bB /etc/nginx/.htpasswd	spoirier@hhof.com RjnX8625+
htpasswd -bB /etc/nginx/.htpasswd	nasilevich@ska.ru MkqM4066*
htpasswd -bB /etc/nginx/.htpasswd	jon.morosi@mlb.com AkeN8141*
htpasswd -bB /etc/nginx/.htpasswd	Mariya.Bass@matchtv.ru RdmM3814*
htpasswd -bB /etc/nginx/.htpasswd	bizone08@mail.ru MesM6641*
htpasswd -bB /etc/nginx/.htpasswd	marie.lehmann@svt.se RqeA4842+
htpasswd -bB /etc/nginx/.htpasswd	erica.karlsson@outlook.com PwqZ5842+
htpasswd -bB /etc/nginx/.htpasswd	timo.kunnari@yellowfilm.fi UidU9293+
htpasswd -bB /etc/nginx/.htpasswd	jill.m.savage@gmail.com OfdM5715+
htpasswd -bB /etc/nginx/.htpasswd	Mark.Masters@bellmedia.ca SsiT3070*
htpasswd -bB /etc/nginx/.htpasswd	Corwin.Mccallum@bellmedia.ca QytD2957+
htpasswd -bB /etc/nginx/.htpasswd	Patrick.Friolet@bellmedia.ca YcmI1314+
htpasswd -bB /etc/nginx/.htpasswd	Mike.Whittingham@bellmedia.ca TmnX8077*
htpasswd -bB /etc/nginx/.htpasswd	Blake.Price@bellmedia.ca NdoN1328+
htpasswd -bB /etc/nginx/.htpasswd	dave.tomlinson@shaw.ca OmgD9896+
htpasswd -bB /etc/nginx/.htpasswd	Steve.Dryden@bellmedia.ca VtiA3138+
htpasswd -bB /etc/nginx/.htpasswd	dennis.beyak@bellmedia.ca KhgQ9538*
htpasswd -bB /etc/nginx/.htpasswd	Craig.Button@bellmedia.ca UxyP7758+
htpasswd -bB /etc/nginx/.htpasswd	Ray.Ferraro@bellmedia.ca UohG4735*
htpasswd -bB /etc/nginx/.htpasswd	Gord.Miller@bellmedia.ca AmcH6077+
htpasswd -bB /etc/nginx/.htpasswd	Laura.Diakun@bellmedia.ca JbhK2427*
htpasswd -bB /etc/nginx/.htpasswd	bob.mckenziemedia@gmail.com IawB4084*
htpasswd -bB /etc/nginx/.htpasswd	James.Duthie@bellmedia.ca KjwS8362*
htpasswd -bB /etc/nginx/.htpasswd	Lars.Nay@mysports.ch DbvI2931*
htpasswd -bB /etc/nginx/.htpasswd	Ken.Vettore@mysports.ch ThxV8481+
htpasswd -bB /etc/nginx/.htpasswd	Anina.Stierli@mysports.ch AfaH6074+
htpasswd -bB /etc/nginx/.htpasswd	martin.mcguire@cogecodiffusion.com FjnB2531+
htpasswd -bB /etc/nginx/.htpasswd	jtremblay@lapresse.ca JjtU2471+
htpasswd -bB /etc/nginx/.htpasswd	kmoore@cjob.com WvvA4388+
htpasswd -bB /etc/nginx/.htpasswd	glenn.campbell@bellmedia.ca OrtD5461*
htpasswd -bB /etc/nginx/.htpasswd	c_stadtler@web.de ZhaB9138+
htpasswd -bB /etc/nginx/.htpasswd	Marek.marusiak@rtvs.sk HlbA8633*
htpasswd -bB /etc/nginx/.htpasswd	kruk_a@tass.ru IacB9957*
htpasswd -bB /etc/nginx/.htpasswd	sharafutdinov_r@tass.ru HxhR7620+
htpasswd -bB /etc/nginx/.htpasswd	Tesar@ctk.cz WgmG3333*
htpasswd -bB /etc/nginx/.htpasswd	rob.mcanally@bellmedia.ca TxoX4304+
htpasswd -bB /etc/nginx/.htpasswd	mbrunet@lapresse.ca YpiX8115+

sed \
  -e "s/##CLIENT_MAX_BODY_SIZE##/$CLIENT_MAX_BODY_SIZE/g" \
  -e "s/##PROXY_READ_TIMEOUT##/$PROXY_READ_TIMEOUT/g" \
  -e "s/##WORKER_PROCESSES##/$WORKER_PROCESSES/g" \
  -e "s/##SERVER_NAME##/$SERVER_NAME/g" \
  -e "s/##PORT##/$PORT/g" \
  -e "s|##PROXY_PASS##|$PROXY_PASS|g" \
  nginx.conf.tmpl > /etc/nginx/nginx.conf

exec nginx -g "daemon off;"
